<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>泛家居供应链管理系统接口测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.9.1"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    
<style type="text/css" media="screen">
    body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
    table       { font-size: 100%; }
    pre         { white-space: pre-wrap;word-wrap: break-word; }

    /* -- heading ---------------------------------------------------------------------- */
    h1 {
        font-size: 16pt;
        color: gray;
    }
    .heading {
        margin-top: 0ex;
        margin-bottom: 1ex;
    }

    .heading .attribute {
        margin-top: 1ex;
        margin-bottom: 0;
    }

    .heading .description {
        margin-top: 2ex;
        margin-bottom: 3ex;
    }

    /* -- css div popup ------------------------------------------------------------------------ */
    a.popup_link {
    }

    a.popup_link:hover {
        color: red;
    }

    .popup_window {
        display: none;
        position: relative;
        left: 0px;
        top: 0px;
        /*border: solid #627173 1px; */
        padding: 10px;
        /*background-color: #E6E6D6; */
        font-family: "Lucida Console", "Courier New", Courier, monospace;
        text-align: left;
        font-size: 8pt;
        /* width: 500px;*/
    }

    }
    /* -- report ------------------------------------------------------------------------ */
    #show_detail_line {
        margin-top: 3ex;
        margin-bottom: 1ex;
    }
    #result_table {
        width: 99%;
    }
    #header_row {
        font-weight: bold;
        color: #303641;
        background-color: #ebebeb;
    }
    #total_row  { font-weight: bold; }
    .passClass  { background-color: #bdedbc; }
    .failClass  { background-color: #ffefa4; }
    .errorClass { background-color: #ffc9c9; }
    .passCase   { color: #6c6; }
    .failCase   { color: #FF6600; font-weight: bold; }
    .errorCase  { color: #c00; font-weight: bold; }
    .hiddenRow  { display: none; }
    .testcase   { margin-left: 2em; }


    /* -- ending ---------------------------------------------------------------------- */
    #ending {
    }

    #div_base {
                position:absolute;
                top:0%;
                left:5%;
                right:5%;
                width: auto;
                height: auto;
                margin: -15px 0 0 0;
    }
</style>

    <link href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" src="js/echarts.common.min.js"></script>
</head>
<body>
    <script language="javascript" type="text/javascript"><!--
    output_list = Array();

    /* level - 0:Summary; 1:Failed; 2:All */
    function showCase(level) {
        trs = document.getElementsByTagName("tr");
        for (var i = 0; i < trs.length; i++) {
            tr = trs[i];
            id = tr.id;
            if (id.substr(0,2) == 'ft') {
                if (level < 1) {
                    tr.className = 'hiddenRow';
                }
                else {
                    tr.className = '';
                }
            }
            if (id.substr(0,2) == 'pt') {
                if (level > 1) {
                    tr.className = '';
                }
                else {
                    tr.className = 'hiddenRow';
                }
            }
        }
    }


    function showClassDetail(cid, count) {
        var id_list = Array(count);
        var toHide = 1;
        for (var i = 0; i < count; i++) {
            tid0 = 't' + cid.substr(1) + '.' + (i+1);
            tid = 'f' + tid0;
            tr = document.getElementById(tid);
            if (!tr) {
                tid = 'p' + tid0;
                tr = document.getElementById(tid);
            }
            id_list[i] = tid;
            if (tr.className) {
                toHide = 0;
            }
        }
        for (var i = 0; i < count; i++) {
            tid = id_list[i];
            if (toHide) {
                document.getElementById('div_'+tid).style.display = 'none'
                document.getElementById(tid).className = 'hiddenRow';
            }
            else {
                document.getElementById(tid).className = '';
            }
        }
    }


    function showTestDetail(div_id){
        var details_div = document.getElementById(div_id)
        var displayState = details_div.style.display
        // alert(displayState)
        if (displayState != 'block' ) {
            displayState = 'block'
            details_div.style.display = 'block'
        }
        else {
            details_div.style.display = 'none'
        }
    }


    function html_escape(s) {
        s = s.replace(/&/g,'&amp;');
        s = s.replace(/</g,'&lt;');
        s = s.replace(/>/g,'&gt;');
        return s;
    }

    /* obsoleted by detail in <div>
    function showOutput(id, name) {
        var w = window.open("", //url
                        name,
                        "resizable,scrollbars,status,width=800,height=450");
        d = w.document;
        d.write("<pre>");
        d.write(html_escape(output_list[id]));
        d.write("\n");
        d.write("<a href='javascript:window.close()'>close</a>\n");
        d.write("</pre>\n");
        d.close();
    }
    */
    --></script>

    <div id="div_base">
        
    <div class='page-header'>
        <h1>泛家居供应链管理系统接口测试报告</h1>
    <p class='attribute'><strong>开始时间:</strong> 2017-11-18 14:19:22</p>
<p class='attribute'><strong>运行时长:</strong> 0:00:03.102879</p>
<p class='attribute'><strong>状态:</strong> 通过 1 失败 109</p>

    </div>
    <div style="float: left;width:50%;"><p class='description'></p></div>
    <div id="chart" style="width:50%;height:400px;float:left;"></div>

        
    <div class="btn-group btn-group-sm">
        <button class="btn btn-default" onclick='javascript:showCase(0)'>总结</button>
        <button class="btn btn-default" onclick='javascript:showCase(1)'>失败</button>
        <button class="btn btn-default" onclick='javascript:showCase(2)'>全部</button>
    </div>
    <p></p>
    <table id='result_table' class="table table-bordered">
        <colgroup>
            <col align='left' />
            <col align='right' />
            <col align='right' />
            <col align='right' />
            <col align='right' />
            <col align='right' />
        </colgroup>
        <tr id='header_row'>
            <td>测试套件/测试用例</td>
            <td>总数</td>
            <td>通过</td>
            <td>失败</td>
            <td>错误</td>
            <td>查看</td>
        </tr>
        
    <tr class='failClass'>
        <td>testAppAppointDistributionCase.TestAppAppointDistributionCase</td>
        <td>4</td>
        <td>0</td>
        <td>4</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c1',4)">详情</a></td>
    </tr>

<tr id='ft1.1' class='none'>
    <td class='failCase'><div class='testcase'>test_alreadyAppointSearch: 已预约</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.1')" >
        失败</a>

    <div id='div_ft1.1' class="popup_window">
        <pre>
        ft1.1: 
1 已预约

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_alreadyAppointSearch (testAppAppointDistributionCase.TestAppAppointDistributionCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.2' class='none'>
    <td class='failCase'><div class='testcase'>test_alreadyArriveSearch: 已到件</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.2')" >
        失败</a>

    <div id='div_ft1.2' class="popup_window">
        <pre>
        ft1.2: 
1 已到件

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_alreadyArriveSearch (testAppAppointDistributionCase.TestAppAppointDistributionCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.3' class='none'>
    <td class='failCase'><div class='testcase'>test_orderNotArriveSearch: 未到件</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.3')" >
        失败</a>

    <div id='div_ft1.3' class="popup_window">
        <pre>
        ft1.3: 
1 未到件

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderNotArriveSearch (testAppAppointDistributionCase.TestAppAppointDistributionCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft1.4' class='none'>
    <td class='failCase'><div class='testcase'>test_serviceOrderSearch: 服务中</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft1.4')" >
        失败</a>

    <div id='div_ft1.4' class="popup_window">
        <pre>
        ft1.4: 
1 服务中

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_serviceOrderSearch (testAppAppointDistributionCase.TestAppAppointDistributionCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testAppOrderTurnCase.TestAppOrderTurnCase</td>
        <td>2</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c2',2)">详情</a></td>
    </tr>

<tr id='ft2.1' class='none'>
    <td class='failCase'><div class='testcase'>test_auditRecordSearch: 审核记录</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.1')" >
        失败</a>

    <div id='div_ft2.1' class="popup_window">
        <pre>
        ft2.1: 
1 审核记录

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_auditRecordSearch (testAppOrderTurnCase.TestAppOrderTurnCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft2.2' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTurnAuditSearch: 转单审核</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft2.2')" >
        失败</a>

    <div id='div_ft2.2' class="popup_window">
        <pre>
        ft2.2: 
1 转单审核

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTurnAuditSearch (testAppOrderTurnCase.TestAppOrderTurnCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testAppPendingOrder_case.TestAppPendingOrderCase</td>
        <td>5</td>
        <td>0</td>
        <td>5</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c3',5)">详情</a></td>
    </tr>

<tr id='ft3.1' class='none'>
    <td class='failCase'><div class='testcase'>test_abnormalSearch: 异常</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.1')" >
        失败</a>

    <div id='div_ft3.1' class="popup_window">
        <pre>
        ft3.1: 
1 异常

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_abnormalSearch (testAppPendingOrder_case.TestAppPendingOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.2' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 全部订单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.2')" >
        失败</a>

    <div id='div_ft3.2' class="popup_window">
        <pre>
        ft3.2: 
1 全部订单

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testAppPendingOrder_case.TestAppPendingOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.3' class='none'>
    <td class='failCase'><div class='testcase'>test_houseCallSearch: 待上门</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.3')" >
        失败</a>

    <div id='div_ft3.3' class="popup_window">
        <pre>
        ft3.3: 
1 待上门

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_houseCallSearch (testAppPendingOrder_case.TestAppPendingOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.4' class='none'>
    <td class='failCase'><div class='testcase'>test_pickUpGoodsSearch: 待提货</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.4')" >
        失败</a>

    <div id='div_ft3.4' class="popup_window">
        <pre>
        ft3.4: 
1 待提货

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_pickUpGoodsSearch (testAppPendingOrder_case.TestAppPendingOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft3.5' class='none'>
    <td class='failCase'><div class='testcase'>test_signSearch: 待签收</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft3.5')" >
        失败</a>

    <div id='div_ft3.5' class="popup_window">
        <pre>
        ft3.5: 
1 待签收

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_signSearch (testAppPendingOrder_case.TestAppPendingOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testAppSignOrderCase.TestAppSignOrderCase</td>
        <td>2</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c4',2)">详情</a></td>
    </tr>

<tr id='ft4.1' class='none'>
    <td class='failCase'><div class='testcase'>test_signedOrderSearch: 已签收订单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.1')" >
        失败</a>

    <div id='div_ft4.1' class="popup_window">
        <pre>
        ft4.1: 
1 已签收订单

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 已签收订单

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_signedOrderSearch (testAppSignOrderCase.TestAppSignOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft4.2' class='none'>
    <td class='failCase'><div class='testcase'>test_signedOrderSearch: 已签收订单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft4.2')" >
        失败</a>

    <div id='div_ft4.2' class="popup_window">
        <pre>
        ft4.2: 
1 已签收订单

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 已签收订单

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_signedOrderSearch (testAppSignOrderCase.TestAppSignOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testAppSignOrderCase1.TestAppSignOrderCase</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c5',1)">详情</a></td>
    </tr>

<tr id='ft5.1' class='none'>
    <td class='failCase'><div class='testcase'>test_signedOrderSearch: 已签收订单详情</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft5.1')" >
        失败</a>

    <div id='div_ft5.1' class="popup_window">
        <pre>
        ft5.1: 
1 已签收订单详情

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_signedOrderSearch (testAppSignOrderCase1.TestAppSignOrderCase) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebBackendSearch.TestWebBackendSearch</td>
        <td>17</td>
        <td>0</td>
        <td>17</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c6',17)">详情</a></td>
    </tr>

<tr id='ft6.1' class='none'>
    <td class='failCase'><div class='testcase'>test_addFeeAuditSearch: 增值审核</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.1')" >
        失败</a>

    <div id='div_ft6.1' class="popup_window">
        <pre>
        ft6.1: 
1 增值审核-待审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 增值审核-已审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 增值审核-网点类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_addFeeAuditSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.2' class='none'>
    <td class='failCase'><div class='testcase'>test_addFeeAuditSearch: 增值审核</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.2')" >
        失败</a>

    <div id='div_ft6.2' class="popup_window">
        <pre>
        ft6.2: 
1 增值审核-待审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 增值审核-已审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 增值审核-网点类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_addFeeAuditSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.3' class='none'>
    <td class='failCase'><div class='testcase'>test_addFeeAuditSearch: 增值审核</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.3')" >
        失败</a>

    <div id='div_ft6.3' class="popup_window">
        <pre>
        ft6.3: 
1 增值审核-待审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 增值审核-已审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 增值审核-网点类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_addFeeAuditSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.4' class='none'>
    <td class='failCase'><div class='testcase'>test_clearingCostSearch: 大区结算查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.4')" >
        失败</a>

    <div id='div_ft6.4' class="popup_window">
        <pre>
        ft6.4: 
1 大区结算列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 大区结算-获取师傅信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_clearingCostSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.5' class='none'>
    <td class='failCase'><div class='testcase'>test_clearingCostSearch: 大区结算查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.5')" >
        失败</a>

    <div id='div_ft6.5' class="popup_window">
        <pre>
        ft6.5: 
1 大区结算列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 大区结算-获取师傅信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_clearingCostSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.6' class='none'>
    <td class='failCase'><div class='testcase'>test_confirmCostSearch: 大区成本查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.6')" >
        失败</a>

    <div id='div_ft6.6' class="popup_window">
        <pre>
        ft6.6: 
1 大区成本列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 大区成本-服务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 大区成本-业务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_confirmCostSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.7' class='none'>
    <td class='failCase'><div class='testcase'>test_confirmCostSearch: 大区成本查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.7')" >
        失败</a>

    <div id='div_ft6.7' class="popup_window">
        <pre>
        ft6.7: 
1 大区成本列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 大区成本-服务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 大区成本-业务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_confirmCostSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.8' class='none'>
    <td class='failCase'><div class='testcase'>test_confirmCostSearch: 大区成本查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.8')" >
        失败</a>

    <div id='div_ft6.8' class="popup_window">
        <pre>
        ft6.8: 
1 大区成本列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 大区成本-服务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 大区成本-业务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_confirmCostSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.9' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTurnSearch: 末端转单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.9')" >
        失败</a>

    <div id='div_ft6.9' class="popup_window">
        <pre>
        ft6.9: 
1 末端转单列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTurnSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.10' class='none'>
    <td class='failCase'><div class='testcase'>test_payCostSearch: 大区支付查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.10')" >
        失败</a>

    <div id='div_ft6.10' class="popup_window">
        <pre>
        ft6.10: 
1 大区支付-未支付列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 大区支付-已支付列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_payCostSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.11' class='none'>
    <td class='failCase'><div class='testcase'>test_payCostSearch: 大区支付查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.11')" >
        失败</a>

    <div id='div_ft6.11' class="popup_window">
        <pre>
        ft6.11: 
1 大区支付-未支付列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 大区支付-已支付列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_payCostSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.12' class='none'>
    <td class='failCase'><div class='testcase'>test_takeOperationSearch: 代操作查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.12')" >
        失败</a>

    <div id='div_ft6.12' class="popup_window">
        <pre>
        ft6.12: 
1 代操作-代办列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 代操作-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 代操作-订单状态查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 代操作-订单标识查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_takeOperationSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.13' class='none'>
    <td class='failCase'><div class='testcase'>test_takeOperationSearch: 代操作查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.13')" >
        失败</a>

    <div id='div_ft6.13' class="popup_window">
        <pre>
        ft6.13: 
1 代操作-代办列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 代操作-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 代操作-订单状态查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 代操作-订单标识查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_takeOperationSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.14' class='none'>
    <td class='failCase'><div class='testcase'>test_takeOperationSearch: 代操作查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.14')" >
        失败</a>

    <div id='div_ft6.14' class="popup_window">
        <pre>
        ft6.14: 
1 代操作-代办列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 代操作-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 代操作-订单状态查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 代操作-订单标识查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_takeOperationSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.15' class='none'>
    <td class='failCase'><div class='testcase'>test_takeOperationSearch: 代操作查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.15')" >
        失败</a>

    <div id='div_ft6.15' class="popup_window">
        <pre>
        ft6.15: 
1 代操作-代办列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 代操作-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 代操作-订单状态查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 代操作-订单标识查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_takeOperationSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.16' class='none'>
    <td class='failCase'><div class='testcase'>test_verifiyChangeSearch: 核销变更</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.16')" >
        失败</a>

    <div id='div_ft6.16' class="popup_window">
        <pre>
        ft6.16: 
1 核销变更列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 核销变更-订单来源查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_verifiyChangeSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft6.17' class='none'>
    <td class='failCase'><div class='testcase'>test_verifiyChangeSearch: 核销变更</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft6.17')" >
        失败</a>

    <div id='div_ft6.17' class="popup_window">
        <pre>
        ft6.17: 
1 核销变更列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 核销变更-订单来源查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_verifiyChangeSearch (testWebBackendSearch.TestWebBackendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebBranchOrderSearch.TestWebBranchOrderSearch</td>
        <td>22</td>
        <td>0</td>
        <td>22</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c7',22)">详情</a></td>
    </tr>

<tr id='ft7.1' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.1')" >
        失败</a>

    <div id='div_ft7.1' class="popup_window">
        <pre>
        ft7.1: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.2' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.2')" >
        失败</a>

    <div id='div_ft7.2' class="popup_window">
        <pre>
        ft7.2: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.3' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.3')" >
        失败</a>

    <div id='div_ft7.3' class="popup_window">
        <pre>
        ft7.3: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.4' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.4')" >
        失败</a>

    <div id='div_ft7.4' class="popup_window">
        <pre>
        ft7.4: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.5' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.5')" >
        失败</a>

    <div id='div_ft7.5' class="popup_window">
        <pre>
        ft7.5: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.6' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.6')" >
        失败</a>

    <div id='div_ft7.6' class="popup_window">
        <pre>
        ft7.6: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.7' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.7')" >
        失败</a>

    <div id='div_ft7.7' class="popup_window">
        <pre>
        ft7.7: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.8' class='none'>
    <td class='failCase'><div class='testcase'>test_orderAppointSearch: 预约列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.8')" >
        失败</a>

    <div id='div_ft7.8' class="popup_window">
        <pre>
        ft7.8: 
1 预约列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderAppointSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.9' class='none'>
    <td class='failCase'><div class='testcase'>test_orderDistributionSearch: 派单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.9')" >
        失败</a>

    <div id='div_ft7.9' class="popup_window">
        <pre>
        ft7.9: 
1 派单-今日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 派单-明日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 派单-后天预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 派单-更晚预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 派单-已超时预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderDistributionSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.10' class='none'>
    <td class='failCase'><div class='testcase'>test_orderDistributionSearch: 派单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.10')" >
        失败</a>

    <div id='div_ft7.10' class="popup_window">
        <pre>
        ft7.10: 
1 派单-今日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 派单-明日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 派单-后天预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 派单-更晚预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 派单-已超时预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderDistributionSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.11' class='none'>
    <td class='failCase'><div class='testcase'>test_orderDistributionSearch: 派单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.11')" >
        失败</a>

    <div id='div_ft7.11' class="popup_window">
        <pre>
        ft7.11: 
1 派单-今日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 派单-明日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 派单-后天预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 派单-更晚预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 派单-已超时预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderDistributionSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.12' class='none'>
    <td class='failCase'><div class='testcase'>test_orderDistributionSearch: 派单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.12')" >
        失败</a>

    <div id='div_ft7.12' class="popup_window">
        <pre>
        ft7.12: 
1 派单-今日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 派单-明日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 派单-后天预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 派单-更晚预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 派单-已超时预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderDistributionSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.13' class='none'>
    <td class='failCase'><div class='testcase'>test_orderDistributionSearch: 派单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.13')" >
        失败</a>

    <div id='div_ft7.13' class="popup_window">
        <pre>
        ft7.13: 
1 派单-今日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 派单-明日预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 派单-后天预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 派单-更晚预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 派单-已超时预约订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderDistributionSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.14' class='none'>
    <td class='failCase'><div class='testcase'>test_orderMonitorinSearch: 服务监控列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.14')" >
        失败</a>

    <div id='div_ft7.14' class="popup_window">
        <pre>
        ft7.14: 
1 服务监控-服务中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务监控-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderMonitorinSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.15' class='none'>
    <td class='failCase'><div class='testcase'>test_orderMonitorinSearch: 服务监控列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.15')" >
        失败</a>

    <div id='div_ft7.15' class="popup_window">
        <pre>
        ft7.15: 
1 服务监控-服务中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务监控-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderMonitorinSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.16' class='none'>
    <td class='failCase'><div class='testcase'>test_orderNotArriveSearch: 未到件列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.16')" >
        失败</a>

    <div id='div_ft7.16' class="popup_window">
        <pre>
        ft7.16: 
1 未到件列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderNotArriveSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.17' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTurnAuditSearch: 转单审核列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.17')" >
        失败</a>

    <div id='div_ft7.17' class="popup_window">
        <pre>
        ft7.17: 
1 转单审核-待审列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 转单审核-已驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 转单审核-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTurnAuditSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.18' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTurnAuditSearch: 转单审核列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.18')" >
        失败</a>

    <div id='div_ft7.18' class="popup_window">
        <pre>
        ft7.18: 
1 转单审核-待审列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 转单审核-已驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 转单审核-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTurnAuditSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.19' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTurnAuditSearch: 转单审核列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.19')" >
        失败</a>

    <div id='div_ft7.19' class="popup_window">
        <pre>
        ft7.19: 
1 转单审核-待审列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 转单审核-已驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 转单审核-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTurnAuditSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.20' class='none'>
    <td class='failCase'><div class='testcase'>test_printListSearch: 打印面单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.20')" >
        失败</a>

    <div id='div_ft7.20' class="popup_window">
        <pre>
        ft7.20: 
1 打印面单-全部列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印面单-未打印订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印面单-已打印订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_printListSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.21' class='none'>
    <td class='failCase'><div class='testcase'>test_printListSearch: 打印面单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.21')" >
        失败</a>

    <div id='div_ft7.21' class="popup_window">
        <pre>
        ft7.21: 
1 打印面单-全部列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印面单-未打印订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印面单-已打印订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_printListSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft7.22' class='none'>
    <td class='failCase'><div class='testcase'>test_printListSearch: 打印面单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft7.22')" >
        失败</a>

    <div id='div_ft7.22' class="popup_window">
        <pre>
        ft7.22: 
1 打印面单-全部列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印面单-未打印订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印面单-已打印订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_printListSearch (testWebBranchOrderSearch.TestWebBranchOrderSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebExceptionHandSearch.TestWebExceptionHandSearch</td>
        <td>11</td>
        <td>0</td>
        <td>11</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c8',11)">详情</a></td>
    </tr>

<tr id='ft8.1' class='none'>
    <td class='failCase'><div class='testcase'>test_abnormalTodoSearch: 异常待办列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.1')" >
        失败</a>

    <div id='div_ft8.1' class="popup_window">
        <pre>
        ft8.1: 
1 异常待办-待办列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印面单-已转交列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印面单-已完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_abnormalTodoSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.2' class='none'>
    <td class='failCase'><div class='testcase'>test_abnormalTodoSearch: 异常待办列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.2')" >
        失败</a>

    <div id='div_ft8.2' class="popup_window">
        <pre>
        ft8.2: 
1 异常待办-待办列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印面单-已转交列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印面单-已完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_abnormalTodoSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.3' class='none'>
    <td class='failCase'><div class='testcase'>test_abnormalTodoSearch: 异常待办列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.3')" >
        失败</a>

    <div id='div_ft8.3' class="popup_window">
        <pre>
        ft8.3: 
1 异常待办-待办列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印面单-已转交列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印面单-已完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_abnormalTodoSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.4' class='none'>
    <td class='failCase'><div class='testcase'>test_abnormalTrackSearch: 异常追踪列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.4')" >
        失败</a>

    <div id='div_ft8.4' class="popup_window">
        <pre>
        ft8.4: 
1 异常追踪-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 异常追踪-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_abnormalTrackSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.5' class='none'>
    <td class='failCase'><div class='testcase'>test_abnormalTrackSearch: 异常追踪列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.5')" >
        失败</a>

    <div id='div_ft8.5' class="popup_window">
        <pre>
        ft8.5: 
1 异常追踪-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 异常追踪-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_abnormalTrackSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.6' class='none'>
    <td class='failCase'><div class='testcase'>test_abnormalTurnSearch: 异常转派列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.6')" >
        失败</a>

    <div id='div_ft8.6' class="popup_window">
        <pre>
        ft8.6: 
1 异常转派列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_abnormalTurnSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.7' class='none'>
    <td class='failCase'><div class='testcase'>test_orderVIPAbnormalSearch: VIP发起列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.7')" >
        失败</a>

    <div id='div_ft8.7' class="popup_window">
        <pre>
        ft8.7: 
1 VIP发起-待发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 VIP发起-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderVIPAbnormalSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.8' class='none'>
    <td class='failCase'><div class='testcase'>test_orderVIPAbnormalSearch: VIP发起列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.8')" >
        失败</a>

    <div id='div_ft8.8' class="popup_window">
        <pre>
        ft8.8: 
1 VIP发起-待发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 VIP发起-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderVIPAbnormalSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.9' class='none'>
    <td class='failCase'><div class='testcase'>test_trunkAbnormalSearch: 干线自提异常列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.9')" >
        失败</a>

    <div id='div_ft8.9' class="popup_window">
        <pre>
        ft8.9: 
1 干线自提异常-未发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 干线自提异常-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 干线自提异常-已处理列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_trunkAbnormalSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.10' class='none'>
    <td class='failCase'><div class='testcase'>test_trunkAbnormalSearch: 干线自提异常列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.10')" >
        失败</a>

    <div id='div_ft8.10' class="popup_window">
        <pre>
        ft8.10: 
1 干线自提异常-未发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 干线自提异常-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 干线自提异常-已处理列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_trunkAbnormalSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft8.11' class='none'>
    <td class='failCase'><div class='testcase'>test_trunkAbnormalSearch: 干线自提异常列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft8.11')" >
        失败</a>

    <div id='div_ft8.11' class="popup_window">
        <pre>
        ft8.11: 
1 干线自提异常-未发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 干线自提异常-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 干线自提异常-已处理列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_trunkAbnormalSearch (testWebExceptionHandSearch.TestWebExceptionHandSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebFrontendSearch.TestWebFrontendSearch</td>
        <td>3</td>
        <td>0</td>
        <td>3</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c9',3)">详情</a></td>
    </tr>

<tr id='ft9.1' class='none'>
    <td class='failCase'><div class='testcase'>test_orderArriveSearch: 到件列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.1')" >
        失败</a>

    <div id='div_ft9.1' class="popup_window">
        <pre>
        ft9.1: 
1 到件列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderArriveSearch (testWebFrontendSearch.TestWebFrontendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.2' class='none'>
    <td class='failCase'><div class='testcase'>test_outBoundSearch: 出库列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.2')" >
        失败</a>

    <div id='div_ft9.2' class="popup_window">
        <pre>
        ft9.2: 
1 出库列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_outBoundSearch (testWebFrontendSearch.TestWebFrontendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft9.3' class='none'>
    <td class='failCase'><div class='testcase'>test_putInStorageSearch: 入库列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft9.3')" >
        失败</a>

    <div id='div_ft9.3' class="popup_window">
        <pre>
        ft9.3: 
1 入库列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_putInStorageSearch (testWebFrontendSearch.TestWebFrontendSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebMerchantSearch.TestWebMerchantSearch</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c10',1)">详情</a></td>
    </tr>

<tr id='ft10.1' class='none'>
    <td class='failCase'><div class='testcase'>test_merchantSearch: 商家列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft10.1')" >
        失败</a>

    <div id='div_ft10.1' class="popup_window">
        <pre>
        ft10.1: 
1 商家订单列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_merchantSearch (testWebMerchantSearch.TestWebMerchantSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebOrderChangeSearch.TestWebOrderChangeSearch</td>
        <td>18</td>
        <td>1</td>
        <td>17</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c11',18)">详情</a></td>
    </tr>

<tr id='ft11.1' class='none'>
    <td class='failCase'><div class='testcase'>test_orderCancelSearch: 订单取消查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.1')" >
        失败</a>

    <div id='div_ft11.1' class="popup_window">
        <pre>
        ft11.1: 
1 订单取消-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单取消-已取消列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 变更原因查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderCancelSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.2' class='none'>
    <td class='failCase'><div class='testcase'>test_orderCancelSearch: 订单取消查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.2')" >
        失败</a>

    <div id='div_ft11.2' class="popup_window">
        <pre>
        ft11.2: 
1 订单取消-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单取消-已取消列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 变更原因查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderCancelSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.3' class='none'>
    <td class='failCase'><div class='testcase'>test_orderCancelSearch: 订单取消查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.3')" >
        失败</a>

    <div id='div_ft11.3' class="popup_window">
        <pre>
        ft11.3: 
1 订单取消-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单取消-已取消列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 变更原因查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderCancelSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.4' class='none'>
    <td class='failCase'><div class='testcase'>test_orderChangeAuditSearch: 变更审核查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.4')" >
        失败</a>

    <div id='div_ft11.4' class="popup_window">
        <pre>
        ft11.4: 
1 变更审核-待审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单变更-已驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单变更-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderChangeAuditSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.5' class='none'>
    <td class='failCase'><div class='testcase'>test_orderChangeAuditSearch: 变更审核查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.5')" >
        失败</a>

    <div id='div_ft11.5' class="popup_window">
        <pre>
        ft11.5: 
1 变更审核-待审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单变更-已驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单变更-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderChangeAuditSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.6' class='none'>
    <td class='failCase'><div class='testcase'>test_orderChangeAuditSearch: 变更审核查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.6')" >
        失败</a>

    <div id='div_ft11.6' class="popup_window">
        <pre>
        ft11.6: 
1 变更审核-待审核列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单变更-已驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单变更-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderChangeAuditSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.7' class='none'>
    <td class='failCase'><div class='testcase'>test_orderChangeSearch: 订单变更查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.7')" >
        失败</a>

    <div id='div_ft11.7' class="popup_window">
        <pre>
        ft11.7: 
1 订单变更-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单变更-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单变更-驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单变更-审核通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderChangeSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.8' class='none'>
    <td class='failCase'><div class='testcase'>test_orderChangeSearch: 订单变更查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.8')" >
        失败</a>

    <div id='div_ft11.8' class="popup_window">
        <pre>
        ft11.8: 
1 订单变更-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单变更-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单变更-驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单变更-审核通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderChangeSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.9' class='none'>
    <td class='failCase'><div class='testcase'>test_orderChangeSearch: 订单变更查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.9')" >
        失败</a>

    <div id='div_ft11.9' class="popup_window">
        <pre>
        ft11.9: 
1 订单变更-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单变更-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单变更-驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单变更-审核通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderChangeSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.10' class='none'>
    <td class='failCase'><div class='testcase'>test_orderChangeSearch: 订单变更查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.10')" >
        失败</a>

    <div id='div_ft11.10' class="popup_window">
        <pre>
        ft11.10: 
1 订单变更-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单变更-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单变更-驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单变更-审核通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderChangeSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.11' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTerminationAuditSearch: 服务终止审核查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.11')" >
        失败</a>

    <div id='div_ft11.11' class="popup_window">
        <pre>
        ft11.11: 
1 服务终止审核-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止审核-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止审核-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTerminationAuditSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.12' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTerminationAuditSearch: 服务终止审核查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.12')" >
        失败</a>

    <div id='div_ft11.12' class="popup_window">
        <pre>
        ft11.12: 
1 服务终止审核-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止审核-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止审核-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTerminationAuditSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.13' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTerminationAuditSearch: 服务终止审核查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.13')" >
        失败</a>

    <div id='div_ft11.13' class="popup_window">
        <pre>
        ft11.13: 
1 服务终止审核-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止审核-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止审核-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_orderTerminationAuditSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.14' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTerminationSearch: 服务终止查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.14')" >
        失败</a>

    <div id='div_ft11.14' class="popup_window">
        <pre>
        ft11.14: 
1 服务终止-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 服务终止-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 服务终止-终止原因查询

返回的状态：200
测试结果：成功！！！  200

SubTestCase Failed:
test_orderTerminationSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.15' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTerminationSearch: 服务终止查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.15')" >
        失败</a>

    <div id='div_ft11.15' class="popup_window">
        <pre>
        ft11.15: 
1 服务终止-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 服务终止-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 服务终止-终止原因查询

返回的状态：200
测试结果：成功！！！  200

SubTestCase Failed:
test_orderTerminationSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.16' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTerminationSearch: 服务终止查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.16')" >
        失败</a>

    <div id='div_ft11.16' class="popup_window">
        <pre>
        ft11.16: 
1 服务终止-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 服务终止-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 服务终止-终止原因查询

返回的状态：200
测试结果：成功！！！  200

SubTestCase Failed:
test_orderTerminationSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft11.17' class='none'>
    <td class='failCase'><div class='testcase'>test_orderTerminationSearch: 服务终止查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft11.17')" >
        失败</a>

    <div id='div_ft11.17' class="popup_window">
        <pre>
        ft11.17: 
1 服务终止-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 服务终止-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 服务终止-终止原因查询

返回的状态：200
测试结果：成功！！！  200

SubTestCase Failed:
test_orderTerminationSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='pt11.18' class='hiddenRow'>
    <td class='none'><div class='testcase'>test_orderTerminationSearch: 服务终止查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_pt11.18')" >
        通过</a>

    <div id='div_pt11.18' class="popup_window">
        <pre>
        pt11.18: 
1 服务终止-可发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 服务终止-审核中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 服务终止-被驳回列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 服务终止-已通过列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 服务终止-终止原因查询

返回的状态：200
测试结果：成功！！！  200

SubTestCase Pass:
test_orderTerminationSearch (testWebOrderChangeSearch.TestWebOrderChangeSearch) (data='pass')
        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebOrderManageSearch.TestWebOrderManageSearch</td>
        <td>19</td>
        <td>0</td>
        <td>19</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c12',19)">详情</a></td>
    </tr>

<tr id='ft12.1' class='none'>
    <td class='failCase'><div class='testcase'>test_TMSOrderSearch: TMS绑单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.1')" >
        失败</a>

    <div id='div_ft12.1' class="popup_window">
        <pre>
        ft12.1: 
1 TMS绑单列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 TMS订单列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_TMSOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.2' class='none'>
    <td class='failCase'><div class='testcase'>test_TMSOrderSearch: TMS绑单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.2')" >
        失败</a>

    <div id='div_ft12.2' class="popup_window">
        <pre>
        ft12.2: 
1 TMS绑单列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 TMS订单列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_TMSOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.3' class='none'>
    <td class='failCase'><div class='testcase'>test_addOrderSearch: 录单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.3')" >
        失败</a>

    <div id='div_ft12.3' class="popup_window">
        <pre>
        ft12.3: 
1 录单-结算主体查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 录单字典-业务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 录单-固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 录单-非固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_addOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.4' class='none'>
    <td class='failCase'><div class='testcase'>test_addOrderSearch: 录单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.4')" >
        失败</a>

    <div id='div_ft12.4' class="popup_window">
        <pre>
        ft12.4: 
1 录单-结算主体查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 录单字典-业务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 录单-固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 录单-非固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_addOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.5' class='none'>
    <td class='failCase'><div class='testcase'>test_addOrderSearch: 录单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.5')" >
        失败</a>

    <div id='div_ft12.5' class="popup_window">
        <pre>
        ft12.5: 
1 录单-结算主体查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 录单字典-业务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 录单-固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 录单-非固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_addOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.6' class='none'>
    <td class='failCase'><div class='testcase'>test_addOrderSearch: 录单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.6')" >
        失败</a>

    <div id='div_ft12.6' class="popup_window">
        <pre>
        ft12.6: 
1 录单-结算主体查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 录单字典-业务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 录单-固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 录单-非固定费用项查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_addOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.7' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.7')" >
        失败</a>

    <div id='div_ft12.7' class="popup_window">
        <pre>
        ft12.7: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.8' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.8')" >
        失败</a>

    <div id='div_ft12.8' class="popup_window">
        <pre>
        ft12.8: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.9' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.9')" >
        失败</a>

    <div id='div_ft12.9' class="popup_window">
        <pre>
        ft12.9: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.10' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.10')" >
        失败</a>

    <div id='div_ft12.10' class="popup_window">
        <pre>
        ft12.10: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.11' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.11')" >
        失败</a>

    <div id='div_ft12.11' class="popup_window">
        <pre>
        ft12.11: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.12' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.12')" >
        失败</a>

    <div id='div_ft12.12' class="popup_window">
        <pre>
        ft12.12: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.13' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.13')" >
        失败</a>

    <div id='div_ft12.13' class="popup_window">
        <pre>
        ft12.13: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.14' class='none'>
    <td class='failCase'><div class='testcase'>test_allOrderSearch: 订单查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.14')" >
        失败</a>

    <div id='div_ft12.14' class="popup_window">
        <pre>
        ft12.14: 
1 订单查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 订单详情-基础信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 订单详情-核销信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

4 订单详情-产品信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

5 订单详情-费用信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

6 订单详情-预约信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

7 订单详情-节点信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

8 订单详情-签收信息

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_allOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.15' class='none'>
    <td class='failCase'><div class='testcase'>test_importDirectSearch: 直营导单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.15')" >
        失败</a>

    <div id='div_ft12.15' class="popup_window">
        <pre>
        ft12.15: 
1 直营导单列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_importDirectSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.16' class='none'>
    <td class='failCase'><div class='testcase'>test_importOrderSearch: 暂存单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.16')" >
        失败</a>

    <div id='div_ft12.16' class="popup_window">
        <pre>
        ft12.16: 
1 暂存单列表

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_importOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.17' class='none'>
    <td class='failCase'><div class='testcase'>test_printOrderSearch: 打印订单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.17')" >
        失败</a>

    <div id='div_ft12.17' class="popup_window">
        <pre>
        ft12.17: 
1 打印字典-服务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印字典-订单状态查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_printOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.18' class='none'>
    <td class='failCase'><div class='testcase'>test_printOrderSearch: 打印订单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.18')" >
        失败</a>

    <div id='div_ft12.18' class="popup_window">
        <pre>
        ft12.18: 
1 打印字典-服务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印字典-订单状态查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_printOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft12.19' class='none'>
    <td class='failCase'><div class='testcase'>test_printOrderSearch: 打印订单</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft12.19')" >
        失败</a>

    <div id='div_ft12.19' class="popup_window">
        <pre>
        ft12.19: 
1 打印字典-服务类型查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 打印字典-订单状态查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

3 打印列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_printOrderSearch (testWebOrderManageSearch.TestWebOrderManageSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

    <tr class='failClass'>
        <td>testWebQualityAssuranceSearch.TestWebQualityAssuranceSearch</td>
        <td>5</td>
        <td>0</td>
        <td>5</td>
        <td>0</td>
        <td><a href="javascript:showClassDetail('c13',5)">详情</a></td>
    </tr>

<tr id='ft13.1' class='none'>
    <td class='failCase'><div class='testcase'>test_qualityHandSearch: 质保处理列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft13.1')" >
        失败</a>

    <div id='div_ft13.1' class="popup_window">
        <pre>
        ft13.1: 
1 质保处理-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 质保处理-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_qualityHandSearch (testWebQualityAssuranceSearch.TestWebQualityAssuranceSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft13.2' class='none'>
    <td class='failCase'><div class='testcase'>test_qualityHandSearch: 质保处理列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft13.2')" >
        失败</a>

    <div id='div_ft13.2' class="popup_window">
        <pre>
        ft13.2: 
1 质保处理-处理中列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

2 质保处理-完结列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_qualityHandSearch (testWebQualityAssuranceSearch.TestWebQualityAssuranceSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft13.3' class='none'>
    <td class='failCase'><div class='testcase'>test_qualityStartSearch: 质保发起列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft13.3')" >
        失败</a>

    <div id='div_ft13.3' class="popup_window">
        <pre>
        ft13.3: 
1 质保发起列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_qualityStartSearch (testWebQualityAssuranceSearch.TestWebQualityAssuranceSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft13.4' class='none'>
    <td class='failCase'><div class='testcase'>test_qualitySubOrderSearch: 质保衍生单列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft13.4')" >
        失败</a>

    <div id='div_ft13.4' class="popup_window">
        <pre>
        ft13.4: 
1 质保衍生单列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_qualitySubOrderSearch (testWebQualityAssuranceSearch.TestWebQualityAssuranceSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

<tr id='ft13.5' class='none'>
    <td class='failCase'><div class='testcase'>test_qualityTurnSearch: 质保转派列表查询</div></td>
    <td colspan='5' align='center'>

    <!--css div popup start-->
    <a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_ft13.5')" >
        失败</a>

    <div id='div_ft13.5' class="popup_window">
        <pre>
        ft13.5: 
1 质保转派列表查询

返回的状态：401
测试结果：失败！！！  401
返回的数据：{"msg":"Your token is out time .Please log in again. ","status":"error"}

SubTestCase Failed:
test_qualityTurnSearch (testWebQualityAssuranceSearch.TestWebQualityAssuranceSearch) (data='fail')Traceback (most recent call last):
  File "/Users/snolia/PycharmProjects/SCM3.0/AthenaTest/common/loadDatas.py", line 52, in loadDatas
    self.assertEqual(result, "pass")
AssertionError: 'fail' != 'pass'
- fail
+ pass


        </pre>
    </div>
    <!--css div popup end-->

    </td>
</tr>

        <tr id='total_row'>
            <td>总计</td>
            <td>110</td>
            <td>1</td>
            <td>109</td>
            <td>0</td>
            <td>&nbsp;</td>
        </tr>
    </table>

        <div id='ending'>&nbsp;</div>
        
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('chart'));

        // 指定图表的配置项和数据
        var option = {
            title : {
                text: '测试执行情况',
                x:'center'
            },
            tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left',
                data: ['通过','失败','错误']
            },
            series : [
                {
                    name: '测试执行情况',
                    type: 'pie',
                    radius : '60%',
                    center: ['50%', '60%'],
                    data:[
                        {value:1, name:'通过'},
                        {value:109, name:'失败'},
                        {value:0, name:'错误'}
                    ],
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
    
    </div>
</body>
</html>
